// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdlwhlxbcmpxtzwoobqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkbHdobHhiY21weHR6d29vYnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjQyOTcsImV4cCI6MjA2NTM0MDI5N30.S0QejL0tgsBY3LwiQx_LBOMBIX9WB4nae3jLZAT_rVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);